services:
  invoice-collector:
    image: invoice-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - REGISTRY_SERVER_ENDPOINT=https://registry.invoice-collector.com
      - DATABASE_URI=mongodb://mongodb:27017
      - SECRET_MANAGER_TYPE=bitwarden
      - SECRET_MANAGER_BITWARDEN_API_URI=https://vault.bitwarden.eu/api
      - SECRET_MANAGER_BITWARDEN_IDENTITY_URI=https://vault.bitwarden.eu/identity
      - SECRET_MANAGER_BITWARDEN_ACCESS_TOKEN=
      - SECRET_MANAGER_BITWARDEN_ORGANIZATION_ID=
      - SECRET_MANAGER_BITWARDEN_PROJECT_ID=
      - LOG_SERVER_ACCESS_TOKEN=
    command: npm run start

  mongodb:
    image : mongo:8.0.3
    container_name: mongodb
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/config:/etc/mongo/
    ports:
      - 27017:27017
    command: --logpath /dev/null
