services:
  invoice-collector:
    image: invoice-collector-debug:latest
    build:
      context: .
      dockerfile: Dockerfile-debug
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - LOG_SERVER_ENDPOINT=https://api.invoice-collector.com
      - DATABASE_URI=mongodb://mongodb:27017
      - SECRET_MANAGER_TYPE=bitwarden
      - SECRET_MANAGER_BITWARDEN_API_URI=https://vault.bitwarden.eu/api
      - SECRET_MANAGER_BITWARDEN_IDENTITY_URI=https://vault.bitwarden.eu/identity
    command: npm run debug

  mongodb:
    image : mongo:8.0.3
    container_name: mongodb
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/config:/etc/mongo/
    ports:
      - 27017:27017
    command: --logpath /dev/null
    #command: --quiet --config /etc/mongo/mongod.conf # Quiet option not working
