services:
  invoice-collector:
    image: invoice-collector-debug:latest
    build:
      context: .
      dockerfile: Dockerfile-debug
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - redis
    environment:
      - PORT=8080
      - DATABASE_TYPE=MongoDB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_SERVER_ENDPOINT=https://api.invoice-collector.com
    command: npm run dev

  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379

  mongodb:
    image : mongo:8.0.3
    container_name: mongodb
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/config:/etc/mongo/
    ports:
      - 27017:27017
    command: --logpath /dev/null
    #command: --quiet --config /etc/mongo/mongod.conf # Quiet option not working
