services:
  invoice-collector:
    image: invoice-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_SERVER_ENDPOINT=https://n8n.bergeron.fr/webhook/invoice_collector
    command: npm run start

  redis:
    image: redis:latest
    ports:
      - 6379:6379
