services:
  invoice-collector:
    image: invoice-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_SERVER_ENDPOINT=https://api.invoice-collector.com
      - DATABASE_URI=mongodb://mongodb:27017
      - SECRET_MANAGER_TYPE=bitwarden
      - SECRET_MANAGER_BITWARDEN_API_URI=https://vault.bitwarden.eu/api
      - SECRET_MANAGER_BITWARDEN_IDENTITY_URI=https://vault.bitwarden.eu/identity
    command: npm run start

  redis:
    image: redis:latest
    ports:
      - 6379:6379
