name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'views/**'
      - 'locales/**'
  workflow_dispatch:

env:
  TAG: master
  IMAGE_NAME: ghcr.io/invoice-collector/invoice-collector
  DEPLOYMENT_NAME_DEMO: invoice-collector-demo
  DEPLOYMENT_NAME_PROD: invoice-collector-prod

permissions:
  contents: write
  packages: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        provenance: false
        tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  push-to-kubernetes:
    runs-on: ubuntu-latest
    needs: publish-image

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Reload Demo Deployement
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployment/${{ env.DEPLOYMENT_NAME_DEMO }}

    - name: Reload Prod Deployement
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployment/${{ env.DEPLOYMENT_NAME_PROD }}