name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get package version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.package_version }}"
        else
          VERSION=$(jq -r '.version' package.json)
        fi
        echo "Package version is $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}

  publish-image:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: false
        tags: |
          ghcr.io/invoice-collector/invoice-collector:${{ needs.create-release.outputs.version }}
          ghcr.io/invoice-collector/invoice-collector:latest
