name: Publish image

on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - Create release
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        required: true
        default: '0.1'

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Echo workflow_run
      run: |
        echo ${{ github.event.workflow_run }}

    - name: Echo release
      run: |
        echo ${{ github.event.release }}

    - name: Echo inputs
      run: |
        echo ${{ github.event.inputs }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: false
        tags: |
          ghcr.io/invoice-collector/invoice-collector:${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.tag_name }}
          ghcr.io/invoice-collector/invoice-collector:${{ github.event_name == 'release' && 'latest' || 'draft' }}