name: Tag Latest

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get release tag
      id: get_release_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Update package with latest tag
      run: |
        IMAGE_NAME=ghcr.io/invoice-collector/invoice-collector
        docker pull $IMAGE_NAME:${{ steps.get_release_tag.outputs.tag }}
        docker tag $IMAGE_NAME:${{ steps.get_release_tag.outputs.tag }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
